[firebase_credentials]
type = "service_account"
project_id = "fern-f1e80"
private_key_id = "e684cce0d8479e885582793492540d378c677583"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC7/27DapJQC3UK
UmOsrocrZS/XO70MvbuxNMupYeOvQND/LC3k+dP580BErAV4apNXLKcrA8Fgrx16
jfHZKuN9bGFnD4KWQMYzQ9Mri7l8TIJiU7iAw1/zGEtDeq/wdBtPnPOIzYrxe3mV
...
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@fern-f1e80.iam.gserviceaccount.com"
client_id = "102217501105942568440"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40fern-f1e80.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
